# Generated by Django 3.0.5 on 2021-02-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('facebook_name', models.CharField(max_length=100)),
                ('facebook_email', models.CharField(max_length=100)),
                ('facebook_password', models.CharField(max_length=50)),
                ('facebook_link', models.CharField(max_length=200)),
            ],
        ),
    ]
